### PR TITLE
fixing user access

### PR DESCRIPTION
**Pull request by allaway**
The previous version had two datasets that were not publically accessible. I've changed syn ids to point to the public versions.

### CODE REVIEW

**Comment by allaway** [comment]
thanks! I thought you were an authorized user to merge on this repo but it looks like not.... 🤔

**Comment by allaway** [comment]
@apratap do you know who can merge into master here?

**Comment by xindiguo** [comment]
@allaway I wasn’t sure if you want me to merge it. Now it is merged!

**Comment by allaway** [comment]
Ah, whoops. I saw that I couldn't merge and thought that was because you
weren't listed as a collaborator on this repo, but it's because I'm not a
collaborator on the repo. I need more caffeine...

thanks!!

**Pull request merged**
